@startuml
!include Style.puml

skinparam linetype ortho
skinparam nodesep 100
hide empty members

class Card CARDS_COLOR_PRIMARY

class CardSorter {
  + {static} getSortComparator(\n    criteria: CardSortCriteria \n): Comparator<Card>
  + {static} sort(\n    cards: ArrayList<Card>,\n    criteria:CardSortCriteria, \n    maxLimit: int, \n    defaultMaxLimit: int,    \n    isDescending: boolean \n): ArrayList<Card>
}

CardSorter ..> Card
CardSorter .right.> CardSortCriteria

enum CardSortCriteria <<enumeration>> {
    INDEX
    NAME
    QUANTITY
    PRICE
    SET
    RARITY
    CONDITION
    LANGUAGE
    NUMBER
    NOTE
    ADDED
    MODIFIED
    REMOVED

    + getKeyword(): String
}


}
@enduml